artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/mahfuzrahmandsuh23/All_necessary_data_files/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# In the context of end-to-end deep learning projects, 
# "artifacts" refer to the various outputs and components generated 
# throughout the project lifecycle.
#  These can include data sets, preprocessed data,
#   model files (e.g., weights, architecture), training scripts,
#    environment configuration files (for reproducibility), 
#    logs, and any other files that are produced 
#    or used by the machine learning models.
#     Artifacts are crucial for understanding the project's 
#     evolution, ensuring reproducibility, and facilitating 
# model deployment and monitoring in production environments.

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



 
prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras